import type { Effect } from '../types';

const ARMS = 161;
const FURY = 164;
const PROT = 163;
const ANY = [ARMS, FURY, PROT];

export const WARRIOR_EFFECTS: Effect[] = [
  {
    id: 'battle-shout',
    name: 'Battle Shout',
    icon: 'ability_warrior_battleshout',
    kind: 'buff',
    scope: 'party',
    categories: ['melee-attack-power'],
    providers: [{ classId: 'warrior', specs: ANY }],
    values: { classic: 'Flat melee attack power to the party, 2 min' },
    forever: {
      status: 'changed',
      note: 'Improved Battle Shout is gone from the Fury tree, so every Warrior brings the base value.',
    },
  },
  {
    id: 'demoralizing-shout',
    name: 'Demoralizing Shout',
    icon: 'ability_warrior_warcry',
    kind: 'debuff',
    scope: 'target',
    categories: ['reduced-melee-attack-power'],
    providers: [{ classId: 'warrior', specs: ANY }],
    exclusiveWith: ['demoralizing-roar', 'curse-of-weakness'],
    forever: {
      status: 'changed',
      note: 'Improved Demoralizing Shout was cut from the Fury tree, so this is the base value now.',
    },
  },
  {
    id: 'thunder-clap',
    name: 'Thunder Clap',
    icon: 'spell_nature_thunderclap',
    kind: 'debuff',
    scope: 'target',
    categories: ['reduced-attack-speed'],
    providers: [{ classId: 'warrior', specs: ANY }],
    values: { classic: '10% slower attacks for 30 sec', forever: '20% slower attacks for 22 sec, up to 4 targets' },
    forever: {
      status: 'changed',
      note: 'Works in Battle or Defensive Stance now. Rank 4 slows attacks 20% for 22 sec and hits up to 4 targets.',
    },
  },
  {
    id: 'sunder-armor',
    name: 'Sunder Armor',
    icon: 'ability_warrior_sunder',
    kind: 'debuff',
    scope: 'target',
    categories: ['reduced-armor'],
    providers: [{ classId: 'warrior', specs: ANY }],
    exclusiveWith: ['expose-armor'],
    forever: { status: 'same', note: 'Improved Sunder Armor now only cuts the Rage cost.' },
  },
  {
    id: 'mortal-strike-debuff',
    name: 'Mortal Strike',
    icon: 'ability_warrior_savageblow',
    kind: 'list',
    scope: 'target',
    categories: ['misc-utility'],
    debuffSlots: 0,
    providers: [{ classId: 'warrior', specs: [ARMS], talent: { tree: 'Arms', name: 'Mortal Strike' } }],
    forever: { status: 'same' },
  },
  {
    id: 'challenging-shout',
    name: 'Challenging Shout',
    icon: 'ability_bullrush',
    kind: 'list',
    scope: 'self',
    categories: ['external-cooldowns'],
    providers: [{ classId: 'warrior', specs: ANY }],
    forever: { status: 'same' },
  },
  {
    id: 'intimidating-shout',
    name: 'Intimidating Shout',
    icon: 'ability_golemthunderclap',
    kind: 'list',
    scope: 'self',
    categories: ['in-combat-cc'],
    providers: [{ classId: 'warrior', specs: ANY }],
    forever: { status: 'same' },
  },
  {
    id: 'shield-bash',
    name: 'Shield Bash',
    icon: 'ability_warrior_shieldbash',
    kind: 'other',
    scope: 'self',
    categories: ['interrupts'],
    providers: [{ classId: 'warrior', specs: ANY }],
    forever: { status: 'same' },
  },
  {
    id: 'improved-shield-bash',
    name: 'Improved Shield Bash',
    icon: 'ability_warrior_shieldbash',
    kind: 'other',
    scope: 'self',
    categories: ['silences'],
    providers: [
      { classId: 'warrior', specs: [PROT], talent: { tree: 'Protection', name: 'Improved Shield Bash' } },
    ],
    forever: { status: 'same' },
  },
  {
    id: 'pummel',
    name: 'Pummel',
    icon: 'inv_gauntlets_04',
    kind: 'other',
    scope: 'self',
    categories: ['interrupts'],
    providers: [{ classId: 'warrior', specs: ANY }],
    forever: { status: 'same' },
  },
  {
    id: 'concussion-blow',
    name: 'Concussion Blow',
    icon: 'ability_thunderbolt',
    kind: 'list',
    scope: 'self',
    categories: ['in-combat-cc'],
    providers: [
      { classId: 'warrior', specs: [PROT], talent: { tree: 'Protection', name: 'Concussion Blow' } },
    ],
    forever: { status: 'unverified' },
  },
  {
    id: 'piercing-howl',
    name: 'Piercing Howl',
    icon: 'spell_shadow_deathscream',
    kind: 'debuff',
    scope: 'target',
    categories: ['reduced-movement-speed'],
    debuffSlots: 0,
    providers: [{ classId: 'warrior', specs: [FURY], talent: { tree: 'Fury', name: 'Piercing Howl' } }],
    forever: { status: 'unverified' },
  },
  {
    id: 'disarm',
    name: 'Disarm',
    icon: 'ability_warrior_disarm',
    kind: 'list',
    scope: 'self',
    categories: ['misc-utility'],
    providers: [{ classId: 'warrior', specs: ANY }],
    forever: { status: 'changed', note: 'Improved Disarm now cuts the cooldown by up to 7 sec per rank.' },
  },
  {
    id: 'intercept',
    name: 'Intercept',
    icon: 'ability_rogue_sprint',
    kind: 'list',
    scope: 'self',
    categories: ['external-cooldowns'],
    providers: [{ classId: 'warrior', specs: ANY }],
    forever: {
      status: 'changed',
      note: 'Still in the game via Improved Intercept in Fury, but it was not in the level 38 spellbook, so it is probably learned later than 30 now.',
    },
  },
];
